security:

    # Les encodeurs disponibles pour les types d'utilisateurs du système
    encoders:
        # plaintext = en clair / auto = prend le meilleur disponible sur le système
        # en 2021 soit bcrypt soit argon2
        # Symfony\Component\Security\Core\User\User: auto
        App\Entity\User:
            algorithm: auto



    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    # Endroits où peuvent se trouver nos utilisateurs
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                # Propriété de connexion
                property: email
    # Les firewalls sont un ensemble de règles de sécurité
    # qui régissent le fonctionnement de la sécurité de notre appli
    firewalls:
        # Le firewall de "dev"
        # permet de désactiver la sécurité les URLs du Profiler
        # et de la Web Debug Toolbar et des dossiers d'assets
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # Notre firewall principal
        main:
            # Anonyme autorisé
            anonymous: true
            # Session User démarrée que si on cherche à se connecter
            lazy: true
            # Où sont les utilisateurs ?
            provider: app_user_provider

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # Authentification via "HTTP BASIC"
            # http_basic: true

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true


            # Login en API/JSON
            # @see https://symfony.com/doc/current/security/json_login_setup.html
            json_login:
                check_path: /api/login


            # Déconnexion
            logout:
                # Soit un chemin (endpoint, /logout), soit un nom de route
                path: app_logout

            # Classe qui nous connecte via le formulaire de login Web   
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:

        # Web/HTML

        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

        # Les routes d'ajout, modification, suppression => Admin
        - { path: ^/back/(movie|job|department|user)/(add|delete|edit), roles: ROLE_ADMIN }
        # Pour toutes les autres pages du back => Manager
        - { path: ^/back, roles: ROLE_MANAGER }
        # Pour ajouter une review, il faut etre connecté en tant qu'user
        - { path: ^/review/add, roles: ROLE_USER }

        # Web API
        # ROLE_USER => on doit être connecté au moins en USER pour accéder à l'API
        - { path: ^/api/movies, methods: [GET], roles: ROLE_USER }
        # en ADMIN pour les actions d'écriture
        - { path: ^/api/movies, methods: [POST, PUT, PATCH, DELETE], roles: ROLE_ADMIN }
    
    role_hierarchy:
        # ROLE_ADMIN hérite de ROLE_USER
        # Si pertinent pour le projet
        ROLE_MANAGER: ROLE_USER
        ROLE_ADMIN: [ROLE_MANAGER, ROLE_ALLOWED_TO_SWITCH]
        